# PyTorch Beginner Tutorial
This tutorial will guide you through the fundamentals of PyTorch, from basic tensor operations to building and training neural networks. By the end, you’ll have built a simple convolutional neural network and trained it on the CIFAR-10 dataset.

## 1. Introduction to PyTorch

### What is PyTorch?

PyTorch is a popular open-source deep learning framework that provides a flexible platform for research and production. It is used for building and training neural networks and offers dynamic computation graphs, which means it builds the graph on-the-fly as operations are executed. This is one of the major reasons it is widely adopted by both researchers and practitioners.

### Why PyTorch?

* Easy to use and debug.
* Dynamic computation graph.
* Seamless integration with Python.

### Installation
To install PyTorch, follow these steps:

CPU Version :
```bash
pip install torch torchvision torchaudio
```
GPU Version :
```bash
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
```

## 2. Tensors and Operations

### What are Tensors?
Tensors are the fundamental building blocks of PyTorch, similar to arrays in NumPy but with added functionality for GPU acceleration.

Creating Tensors

In [1]:
import torch

# Create a tensor from a list
x = torch.tensor([[1, 2], [3, 4]])
print(x)

# Create a random tensor
random_tensor = torch.rand(3, 3)
print(random_tensor)


tensor([[1, 2],
        [3, 4]])
tensor([[0.1028, 0.1647, 0.3589],
        [0.7875, 0.9332, 0.4134],
        [0.3297, 0.4527, 0.5389]])


### Basic Tensor Operations

Tensors support various mathematical operations like addition, multiplication, and matrix multiplication.

In [2]:
# Element-wise addition
x = torch.tensor([1.0, 2.0])
y = torch.tensor([3.0, 4.0])
z = x + y
print(z)

# Matrix multiplication
a = torch.rand(2, 3)
b = torch.rand(3, 2)
result = torch.matmul(a, b)
print(result)


tensor([4., 6.])
tensor([[1.1322, 1.1980],
        [0.7644, 0.9101]])


## Autograd: Automatic Differentiation

PyTorch's autograd feature allows automatic computation of gradients for tensor operations, which is essential for training neural networks.

### Example

In [3]:
# Define a tensor with gradient tracking
x = torch.tensor(2.0, requires_grad=True)

# Perform some operations
y = x ** 2

# Backpropagation
y.backward()

# The gradient (dy/dx)
print(x.grad)  # Output: 4.0


tensor(4.)


## Building Neural Networks with PyTorch

We’ll now move on to constructing neural networks using PyTorch’s torch.nn module.

### Creating a Simple Neural Network
Here’s how to define a simple feedforward network with one hidden layer:

In [4]:
import torch.nn as nn

# Define the model
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(10, 50)
        self.fc2 = nn.Linear(50, 1)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x


## Training a Neural Network
### Loss Function and Optimizer
To train the model, we need to define a loss function and an optimizer.

In [5]:
model = SimpleNN()
criterion = nn.MSELoss()  # Mean Squared Error Loss
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)


### Training Loop
Here’s a simple example of a training loop:

In [6]:
# Example training loop
for epoch in range(100):
    optimizer.zero_grad()  # Zero the gradients
    outputs = model(torch.rand(10))  # Dummy input
    loss = criterion(outputs, torch.rand(1))
    loss.backward()  # Backpropagation
    optimizer.step()  # Update weights

    if epoch % 10 == 0:
        print(f'Epoch {epoch}, Loss: {loss.item()}')


Epoch 0, Loss: 0.1818007528781891
Epoch 10, Loss: 0.46184012293815613
Epoch 20, Loss: 0.002310809213668108
Epoch 30, Loss: 0.004846265539526939
Epoch 40, Loss: 0.2919002175331116
Epoch 50, Loss: 0.05440371111035347
Epoch 60, Loss: 7.233682845253497e-05
Epoch 70, Loss: 0.1509057879447937
Epoch 80, Loss: 0.047387998551130295
Epoch 90, Loss: 0.14402790367603302


## Dataset and DataLoader
### Loading a Dataset
PyTorch provides utilities for loading datasets and creating batches using DataLoader. Let’s load the MNIST dataset.

In [7]:
from torch.utils.data import DataLoader
from torchvision.datasets import MNIST
from torchvision.transforms import ToTensor

train_data = MNIST(root='data', train=True, transform=ToTensor(), download=True)
train_loader = DataLoader(dataset=train_data, batch_size=32, shuffle=True)


Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 9912422/9912422 [00:00<00:00, 34066500.64it/s]


Extracting data/MNIST/raw/train-images-idx3-ubyte.gz to data/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 28881/28881 [00:00<00:00, 1059276.60it/s]


Extracting data/MNIST/raw/train-labels-idx1-ubyte.gz to data/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 1648877/1648877 [00:00<00:00, 9685376.33it/s]


Extracting data/MNIST/raw/t10k-images-idx3-ubyte.gz to data/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 4542/4542 [00:00<00:00, 2420344.15it/s]

Extracting data/MNIST/raw/t10k-labels-idx1-ubyte.gz to data/MNIST/raw



## GPU Support
Training on a GPU can significantly speed up the process.

In [8]:
# Check for GPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Move model and data to GPU
model = SimpleNN().to(device)
x = torch.rand(10).to(device)


## Saving and Loading Models
Saving the Model

In [9]:
torch.save(model.state_dict(), 'model.pth')


Loading the model

In [10]:
model.load_state_dict(torch.load('model.pth'))


/tmp/ipykernel_30/165183459.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load('model.pth'))


<All keys matched successfully>

## End-to-End Example: CIFAR-10 Image Classification with CNN
### Overview
In this section, we will build, train, and evaluate a Convolutional Neural Network (CNN) to classify images from the CIFAR-10 dataset. This project will showcase how to use PyTorch for more complex data and how to optimize model training using techniques like data augmentation and GPU acceleration.

### Step 1: Loading and Preprocessing the CIFAR-10 Dataset
We’ll start by loading the CIFAR-10 dataset using PyTorch’s torchvision module and apply transformations like normalization and data augmentation to improve model performance.

In [11]:
import torch
import torchvision
import torchvision.transforms as transforms

# Define transformations including normalization and data augmentation (random cropping, flipping)
transform = transforms.Compose([
    transforms.RandomHorizontalFlip(),  # Randomly flip the image horizontally
    transforms.RandomCrop(32, padding=4),  # Randomly crop the image
    transforms.ToTensor(),  # Convert the image to a tensor
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))  # Normalize based on CIFAR-10 stats
])



# Load the dataset
train_data = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
test_data = torchvision.datasets.CIFAR10(root='./data', train=False, download=True, transform=transform)

# Create data loaders
train_loader = torch.utils.data.DataLoader(train_data, batch_size=64, shuffle=True, num_workers=2)
test_loader = torch.utils.data.DataLoader(test_data, batch_size=64, shuffle=False, num_workers=2)


100%|██████████| 170498071/170498071 [00:01<00:00, 101076407.96it/s]


Extracting ./data/cifar-10-python.tar.gz to ./data
Files already downloaded and verified


### Step 2: Building the CNN Model
We will now define a simple CNN architecture to handle image classification. This model will include convolutional layers for feature extraction and fully connected layers for classification.

In [12]:
import torch.nn as nn
import torch.nn.functional as F

# Define the CNN model
class CNN(nn.Module):
    def __init__(self):
        super(CNN, self).__init__()
        # Convolutional layers
        self.conv1 = nn.Conv2d(3, 32, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, padding=1)
        self.conv3 = nn.Conv2d(64, 128, kernel_size=3, padding=1)

        # Fully connected layers
        self.fc1 = nn.Linear(128 * 4 * 4, 256)  # 128 feature maps, each 4x4 after pooling
        self.fc2 = nn.Linear(256, 10)  # 10 output classes (CIFAR-10 classes)

    def forward(self, x):
        # Apply convolution, ReLU, and max pooling layers
        x = F.relu(self.conv1(x))
        x = F.max_pool2d(x, 2)

        x = F.relu(self.conv2(x))
        x = F.max_pool2d(x, 2)

        x = F.relu(self.conv3(x))
        x = F.max_pool2d(x, 2)

        # Flatten the tensor
        x = x.view(x.size(0), -1)

        # Apply fully connected layers
        x = F.relu(self.fc1(x))
        x = self.fc2(x)

        return x


### Step 3: Setting the Loss Function and Optimizer
We will use the CrossEntropyLoss for classification and Adam as the optimizer to update the model’s weights.

In [13]:
import torch.optim as optim

model = CNN()
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)


### Step 4: Training the Model
We’ll now define the training loop. This loop will:

* Iterate over the training data.
* Compute the loss and gradients.
* Update the model weights using backpropagation.
* Track the loss for monitoring.

In [14]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = model.to(device)

# Training loop
num_epochs = 50
for epoch in range(num_epochs):
    model.train()
    running_loss = 0.0

    for i, (images, labels) in enumerate(train_loader):
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()  # Zero the gradients
        outputs = model(images)  # Forward pass
        loss = criterion(outputs, labels)  # Compute the loss
        loss.backward()  # Backpropagation
        optimizer.step()  # Update weights

        running_loss += loss.item()

        if i % 100 == 99:  # Print every 100 mini-batches
            print(f'Epoch [{epoch+1}/{num_epochs}], Step [{i+1}], Loss: {running_loss/100:.4f}')
            running_loss = 0.0


Epoch [1/50], Step [100], Loss: 1.9832
Epoch [1/50], Step [200], Loss: 1.7155
Epoch [1/50], Step [300], Loss: 1.5699
Epoch [1/50], Step [400], Loss: 1.5121
Epoch [1/50], Step [500], Loss: 1.4827
Epoch [1/50], Step [600], Loss: 1.4244
Epoch [1/50], Step [700], Loss: 1.3767
Epoch [2/50], Step [100], Loss: 1.2884
Epoch [2/50], Step [200], Loss: 1.2303
Epoch [2/50], Step [300], Loss: 1.2106
Epoch [2/50], Step [400], Loss: 1.1932
Epoch [2/50], Step [500], Loss: 1.1693
Epoch [2/50], Step [600], Loss: 1.1259
Epoch [2/50], Step [700], Loss: 1.1138
Epoch [3/50], Step [100], Loss: 1.0613
Epoch [3/50], Step [200], Loss: 1.0539
Epoch [3/50], Step [300], Loss: 1.0102
Epoch [3/50], Step [400], Loss: 0.9991
Epoch [3/50], Step [500], Loss: 0.9978
Epoch [3/50], Step [600], Loss: 0.9764
Epoch [3/50], Step [700], Loss: 0.9199
Epoch [4/50], Step [100], Loss: 0.8976
Epoch [4/50], Step [200], Loss: 0.8880
Epoch [4/50], Step [300], Loss: 0.8804
Epoch [4/50], Step [400], Loss: 0.8741
Epoch [4/50], Step [500],

### Evaluating the Model
Once the model is trained, we can evaluate its performance on the test dataset by calculating the accuracy.

In [15]:
model.eval()  # Set the model to evaluation mode

correct = 0
total = 0
with torch.no_grad():  # No need to compute gradients during evaluation
    for images, labels in test_loader:
        images, labels = images.to(device), labels.to(device)
        outputs = model(images)
        _, predicted = torch.max(outputs.data, 1)  # Get the class with the highest score
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

accuracy = 100 * correct / total
print(f'Accuracy of the model on the 10,000 test images: {accuracy:.2f}%')


Accuracy of the model on the 10,000 test images: 80.40%


### Saving and Loading the Model
After training, we can save the model to disk and reload it later for inference or further training.

In [16]:
# Save the model
torch.save(model.state_dict(), 'cnn_cifar10.pth')

# To load the model later:
# model = CNN()
# model.load_state_dict(torch.load('cnn_cifar10.pth'))
# model.to(device)


### Final Thoughts
* Challenges: While CNNs are effective for image classification tasks, they require careful tuning of hyperparameters such as learning rate, batch size, and architecture complexity.
* Future Work: Experiment with deeper models or advanced techniques like Transfer Learning to improve accuracy on CIFAR-10 or other datasets.

## Conclusion and Next Steps
Congratulations! You’ve built a PyTorch neural network and trained it on the CIFAR-10 dataset. Next, you can experiment with more complex datasets and models, or dive deeper into PyTorch features like:

* Custom datasets
* Advanced optimizers
* Transfer learning